rust: update to 1.32.0.
* Add support for all ppc64 targets.
* Add an 'internal-llvm' option, in case we ever need to build against
  the vendored LLVM instead of system LLVM

Co-authored-by: q66 <daniel@octaforge.org>

https://github.com/void-linux/void-packages/commit/4aa64287db41751191923267bf02f9d9c0ace3fe

diff --git a/srcpkgs/rust/template b/srcpkgs/rust/template
--- a/srcpkgs/rust/template
+++ b/srcpkgs/rust/template
@@ -1,8 +1,8 @@
 maintainer="Andy Weidenbaum <archbaum@gmail.com>"
 pkgname="rust"
-version=1.31.1
+version=1.32.0
 revision=1
-_rust_dist_version=1.31.0
+_rust_dist_version=1.32.0
 _cargo_dist_version=0.32.0
 # NB. if you push any(!) new version, don't forget to put a musl build
 # output in https://alpha.de.repo.voidlinux.org/distfiles/
@@ -10,9 +10,9 @@ short_desc="Safe, concurrent, practical systems language"
 depends="rust-std"
 makedepends+=" libffi-devel"
 makedepends+=" libxml2-devel"
-makedepends+=" llvm"
 makedepends+=" ncurses-devel"
 makedepends+=" zlib-devel"
+makedepends+=" $(vopt_if internal_llvm python-devel llvm)"
 hostmakedepends+=" cmake"
 hostmakedepends+=" curl"
 hostmakedepends+=" pkg-config"
@@ -20,17 +20,19 @@ hostmakedepends+=" python"
 homepage="https://www.rust-lang.org/"
 license="MIT, Apache-2.0"
 distfiles="https://static.rust-lang.org/dist/rustc-$version-src.tar.gz"
-checksum="91d2fc22f08d986adab7a54eb3a6a9b99e490f677d2d092e5b9e4e069c23686a"
+checksum="4c594c7712a0e7e8eae6526c464bf6ea1d82f77b4f61717c3fc28fb27ba2224a"
 wrksrc="rustc-$version-src"
 patch_args="-Np1"
 build_style="configure"
 make_build_args+=" VERBOSE=1"
 make_build_args+=" dist"
+build_options="internal_llvm"
 lib32disabled="yes"
 
 if [[ -n "$CROSS_BUILD" ]]; then
+  broken="build host rustc first"
   hostmakedepends+=" cargo"
-  hostmakedepends+=" llvm"
+  hostmakedepends+=" $(vopt_if internal_llvm '' llvm)"
   # required for building the buildhost's stage0/1
   hostmakedepends+=" libffi-devel"
   hostmakedepends+=" libxml2-devel"
@@ -44,8 +46,8 @@ else
       distfiles+=" https://alpha.de.repo.voidlinux.org/distfiles/rustc-$_rust_dist_version-x86_64-unknown-linux-musl.tar.xz"
       distfiles+=" https://alpha.de.repo.voidlinux.org/distfiles/rust-std-$_rust_dist_version-x86_64-unknown-linux-musl.tar.xz"
       distfiles+=" https://alpha.de.repo.voidlinux.org/distfiles/cargo-$_cargo_dist_version-x86_64-unknown-linux-musl-libressl-2.8.tar.gz"
-      checksum+=" 7ca7360b9243b7117bbb5281b563fdf2bfae61d223ad858199aabc438c828926"
-      checksum+=" b5cadf379e82905459dea5359c7111b30cfbba33a17b6960e3beb72ce79b7db9"
+      checksum+=" 1fa1c8b4b976919e229c8f3ca070ed2235e6f1cecf4967041ef0b8a29a75d517"
+      checksum+=" bfc82c04c46a58ae09be1f32a11a11000830c257969afbf2a270e6eb36d6533a"
       checksum+=" 4dfb1cca7730b38920c04731be0e9d47ec520b3365059b4ccd9c0948346787ea"
       ;;
     x86_64)
@@ -53,8 +55,8 @@ else
       distfiles+=" https://static.rust-lang.org/dist/rustc-$_rust_dist_version-x86_64-unknown-linux-gnu.tar.gz"
       distfiles+=" https://static.rust-lang.org/dist/rust-std-$_rust_dist_version-x86_64-unknown-linux-gnu.tar.gz"
       distfiles+=" https://static.rust-lang.org/dist/cargo-$_cargo_dist_version-x86_64-unknown-linux-gnu.tar.xz"
-      checksum+=" 5c4581f0fc05f0f5076db6231b0c1a4d27eb61c0b36bfb42d97243ad8f4e43a0"
-      checksum+=" fe67a62c7a63acbf2458a36d7689ef41903187a472f0c28850f1fca7ea478da8"
+      checksum+=" 75c31f32e19548c1608611d08b82b87560e02f15caac7b2663a8189a4609977c"
+      checksum+=" 9f2705a3ed3217c13fd55569406c52f590030752f57520312e135223ae930caf"
       checksum+=" 7e46150e431eaafef9439c9cd958aa8d980a0a70f0bb052473f0a75023930dcc"
       ;;
     i686)
@@ -62,9 +64,33 @@ else
       distfiles+=" https://static.rust-lang.org/dist/rustc-$_rust_dist_version-i686-unknown-linux-gnu.tar.gz"
       distfiles+=" https://static.rust-lang.org/dist/rust-std-$_rust_dist_version-i686-unknown-linux-gnu.tar.gz"
       distfiles+=" https://static.rust-lang.org/dist/cargo-$_cargo_dist_version-i686-unknown-linux-gnu.tar.xz"
-      checksum+=" 549116e23dce8687f69327f5ea2c717c93175d24d82d456fab37160f800f8ce8"
-      checksum+=" 14de38321f6f2c64496e77bac793ad5511d37696b9c33283bb6f395dc590c4d9"
+      checksum+=" 45e633c985c259a13d3b096662241bd8255a86ed4917e0fec396e7071c04c734"
+      checksum+=" 69bd6064f605c1d0d7d41070efea1e329d75755b04fbc5a13ffc53efdc3a97c7"
       checksum+=" 200cf76636ccbb153d5c430a5c0f3ad5af206899f76470e3cd046679a5a4ab3f"
+      ;;
+    ppc64le)
+      distfiles+=" https://static.rust-lang.org/dist/rustc-$_rust_dist_version-powerpc64le-unknown-linux-gnu.tar.xz"
+      distfiles+=" https://static.rust-lang.org/dist/rust-std-$_rust_dist_version-powerpc64le-unknown-linux-gnu.tar.xz"
+      distfiles+=" https://alpha.de.repo.voidlinux.org/distfiles/cargo-$_cargo_dist_version-powerpc64le-unknown-linux-gnu.tar.xz"
+      checksum+=" e41bce347e11e9c4868fec2892778e51ed8f3383bd6ee59dd991376c1dea56a9"
+      checksum+=" b281c20115467429573da6b2b5b7a8863f29e203d7919989e71d91e6914d3bbe"
+      checksum+=" bf426e52beb08e0f663b00b23a89053e713ec15c8e6d69b3f5ae85fe23ad7e18"
+      ;;
+    ppc64le-musl)
+      distfiles+=" https://alpha.de.repo.voidlinux.org/distfiles/rustc-$_rust_dist_version-powerpc64le-unknown-linux-musl.tar.xz"
+      distfiles+=" https://alpha.de.repo.voidlinux.org/distfiles/rust-std-$_rust_dist_version-powerpc64le-unknown-linux-musl.tar.xz"
+      distfiles+=" https://alpha.de.repo.voidlinux.org/distfiles/cargo-$_cargo_dist_version-powerpc64le-unknown-linux-musl.tar.xz"
+      checksum+=" bacb713d86be555af4410d685aab475ac63ad66e358f6b00c058253fba275187"
+      checksum+=" 24b6b79356c7bf113ad34f43c14a7a6cec92b9008b05ab58624ce7a353b0e6d0"
+      checksum+=" d9d91997a781753474e89dbb9b7dbbef2f6cfad9387def076d51d654f6bc21fa"
+      ;;
+    ppc64-musl)
+      distfiles+=" https://alpha.de.repo.voidlinux.org/distfiles/rustc-$_rust_dist_version-powerpc64-unknown-linux-musl.tar.xz"
+      distfiles+=" https://alpha.de.repo.voidlinux.org/distfiles/rust-std-$_rust_dist_version-powerpc64-unknown-linux-musl.tar.xz"
+      distfiles+=" https://alpha.de.repo.voidlinux.org/distfiles/cargo-$_cargo_dist_version-powerpc64-unknown-linux-musl.tar.xz"
+      checksum+=" fd090e1329687c1b8e3320b40f0b13640444f93cbb7c235d8491c140337c27df"
+      checksum+=" 791d046ecb3203d90263cddb5f53eafdeb042a55923fea35bbb8db223c892603"
+      checksum+=" ec846d1e9674f60dbd4416d54f74a618288114cea4907b61363adc71b3c8c26f"
       ;;
   esac
 fi
@@ -73,6 +99,15 @@ fi
 # and `host` are the triplets that are supposed to run the built binaries
 # ($CTARGET)
 case $XBPS_MACHINE in
+  ppc64le)
+    _build_triplet="powerpc64le-unknown-linux-gnu"
+    ;;
+  ppc64le-musl)
+    _build_triplet="powerpc64le-unknown-linux-musl"
+    ;;
+  ppc64-musl)
+    _build_triplet="powerpc64-unknown-linux-musl"
+    ;;
   *-musl)
     _build_triplet="${XBPS_MACHINE%-musl}-unknown-linux-musl"
     ;;
@@ -82,7 +117,22 @@ case $XBPS_MACHINE in
 esac
 
 post_extract() {
-  rm -rf src/llvm
+  if [[ -n "$build_option_internal_llvm" ]]; then
+    # patches for rust's bundled llvm
+    pushd src/llvm
+    for x in "$FILESDIR/patches/internal_llvm"/llvm-*.patch; do
+      msg_normal "Applying $x to llvm\n"
+      patch -sNp1 -i "$x"
+    done
+    popd
+  else
+    rm -rf src/llvm
+    # patches for system llvm
+    for x in "$FILESDIR/patches/sys-llvm"/*.patch; do
+      msg_normal "Applying patch $x\n"
+      patch -sNp1 -i "$x"
+    done
+  fi
 
   if [[ -z "$CROSS_BUILD" ]]; then
     mkdir -p stage0
@@ -91,7 +141,7 @@ post_extract() {
     rm ../rust-std-*/rust-std-*/manifest.in
     cp -bflr ../rust-std-*/rust-std-*/* stage0
     case "$XBPS_MACHINE" in
-      *-musl)
+      *-musl|ppc64*)
         cp -bflr ../cargo stage0/bin
         ;;
       *)
@@ -116,14 +166,16 @@ do_configure() {
   configure_args+=" --disable-full-bootstrap"
   configure_args+=" --disable-rpath"
   configure_args+=" --host=$RUST_TARGET"
-  configure_args+=" --llvm-root=/usr"
   configure_args+=" --prefix=/usr"
   configure_args+=" --release-channel=stable"
-  configure_args+=" --set=target.$_build_triplet.llvm-config=/usr/bin/llvm-config"
   configure_args+=" --target=$RUST_TARGET"
-  # jemalloc increases the size of small programs significantly and
-  # provides worse performance in some cases
-  configure_args+=" --disable-jemalloc"
+
+  if ! [[ -n "$build_option_internal_llvm" ]]; then
+    configure_args+=" --enable-llvm-link-shared"
+    configure_args+=" --llvm-root=/usr"
+    configure_args+=" --set=target.$RUST_TARGET.llvm-config=/usr/bin/llvm-config"
+    configure_args+=" --set=target.$_build_triplet.llvm-config=/usr/bin/llvm-config"
+  fi
 
   if [[ -n "$CROSS_BUILD" ]]; then
     configure_args+=" --enable-local-rebuild"
@@ -133,9 +185,6 @@ do_configure() {
     configure_args+=" --set=target.$_build_triplet.cxx=$CXX_host"
     configure_args+=" --set=target.$_build_triplet.ar=$AR_host"
     configure_args+=" --set=target.$_build_triplet.linker=$CC_host"
-    # set 'llvm-config' for the cross target (host) so we don't build
-    # LLVM for it again
-    configure_args+=" --set=target.$RUST_TARGET.llvm-config=/usr/bin/llvm-config"
   else
     configure_args+=" --local-rust-root=$wrksrc/stage0"
   fi
@@ -158,12 +207,13 @@ pre_build() {
   export RUSTFLAGS="-C linker=$CC"
 }
 
+# unset LDFLAGS, otherwise cross builds to the same arch will fail
 do_build() {
   # set the correct CFLAGS for the build host, we have to compile
   # libbacktrace for it during stage1
   # otherwise it attemps to use CFLAGS, which are the CFLAGS of the
   # cross host
-  env CFLAGS_$_build_triplet="$CFLAGS_host" make "$makejobs" $make_build_args
+  env CFLAGS_$_build_triplet="$CFLAGS_host" LDFLAGS='' make "$makejobs" $make_build_args
 }
 
 do_install() {
