tbb: fix Python module installation
https://github.com/void-linux/void-packages/commit/1f5063335f6e57675d1a32ee8acf41f706ba58f9

diff --git a/srcpkgs/tbb/template b/srcpkgs/tbb/template
--- a/srcpkgs/tbb/template
+++ b/srcpkgs/tbb/template
@@ -1,7 +1,7 @@
 maintainer="nox"
 pkgname="tbb"
 version=2021.11.0
-revision=3
+revision=4
 short_desc="Intel Threading Building Blocks"
 makedepends+=" libgomp-devel"
 makedepends+=" libhwloc-devel"
@@ -38,6 +38,36 @@ post_extract() {
       -e "s@#define MALLOC_UNIXLIKE_OVERLOAD_ENABLED __linux__@@" \
       src/tbbmalloc_proxy/proxy.h
   fi
+}
+
+post_install() {
+  # the python package is installed as an egg, which is deprecated and
+  # isn't added to the python path, so just unpack it
+  local sitelib
+
+  sitelib="$DESTDIR/$py3_sitelib"
+
+  for f in "$sitelib"/TBB*-"py$py3_ver"*.egg/EGG-INFO; do
+    [[ -d "$f" ]] || continue
+    mv "$f" "${f%-"py$py3_ver"*.egg/EGG-INFO}-py$py3_ver.egg-info"
+  done
+
+  for f in "$sitelib"/TBB*.egg/*; do
+    [[ -e "$f" ]] || continue
+    mv "$f" "$DESTDIR/$py3_sitelib"
+  done
+
+  # clean up the egg directory to confirm it was successfully unpacked
+  for f in "$sitelib"/*.egg; do
+    [[ -e "$f" ]] || continue
+    rmdir "$f"
+  done
+
+  # make sure the post-install hook finds this shlib for renaming
+  for f in "$sitelib"/tbb/_api*.so; do
+    [[ -e "$f" ]] || continue
+    chmod 0755 "$f"
+  done
 }
 
 tbb-devel_package() {
