binutils: update to 2.35.1
- template is now overhauled
- relro by default
- pic by default (avoids rebuild hack)
- 64-bit bfd can be default
- more reliable target dirs
- default hash style is always set
- build in a separate dir

https://github.com/void-linux/void-packages/commit/e5717ea9a05302328e1f5483efbf6c1512cbb99a

diff --git a/srcpkgs/binutils/template b/srcpkgs/binutils/template
--- a/srcpkgs/binutils/template
+++ b/srcpkgs/binutils/template
@@ -1,7 +1,7 @@
 maintainer="nox"
 pkgname="binutils"
-version=2.34
-revision=2
+version=2.35.1
+revision=1
 short_desc="GNU binary utilities"
 makedepends="zlib-devel"
 if [[ -n "$CHROOT_READY" ]]; then
@@ -15,7 +15,8 @@ fi
 homepage="http://www.gnu.org/software/binutils/"
 license="GPL-3.0-or-later"
 distfiles="$GNU_SITE/binutils/$pkgname-$version.tar.xz"
-checksum="f00b0e8803dc9bab1e2165bd568528135be734df3fabf8d0161828cd56028952"
+checksum="3ced91db9bf01182b7e420eab68039f2083aed0a214c0424e257eae3ddee8607"
+patch_args="-Np1"
 bootstrap="yes"
 
 _get_triplet() {
@@ -30,79 +31,101 @@ _get_triplet() {
 }
 
 do_configure() {
-  local CONFIGFLAG
-  CONFIGFLAG="--build=$(_get_triplet)
-    --prefix=/usr
-    --enable-threads
-    --enable-plugins
-    --enable-secureplt
-    --with-mmap
-    --disable-shared
-    --enable-gold
-    --disable-werror
-    --enable-deterministic-archives
-    --enable-ld=default
-    --disable-nls"
+  local conf
+
   if [[ -n "$CHROOT_READY" ]]; then
-    CONFIGFLAG+=" --with-debuginfod"
+    conf+=" --with-debuginfod"
   else
-    CONFIGFLAG+=" --without-debuginfod"
-  fi
-  if [[ "$XBPS_TARGET_MACHINE" == "x86_64" ]]; then
-    CONFIGFLAG+=" --enable-64-bit-bfd"
-    CONFIGFLAG+=" --enable-multilib"
+    conf+=" --without-debuginfod"
   fi
   if [[ -n "$CROSS_BUILD" ]]; then
-    # do not use configure_args nor build_style=gnu-configure,
-    # avoiding --with-sysroot to $XBPS_CROSS_BASE.
-    CONFIGFLAG+=" --host=$XBPS_CROSS_TRIPLET"
-    CONFIGFLAG+=" --with-build-sysroot=$XBPS_CROSS_BASE"
+    # we don't want --with-sysroot=$XBPS_CROSS_BASE like gnu-configure
+    conf+=" --host=$XBPS_CROSS_TRIPLET"
+    conf+=" --with-build-sysroot=$XBPS_CROSS_BASE"
   fi
-  if [[ "$XBPS_TARGET_MACHINE" == "mips-musl" ]] \
-  || [[ "$XBPS_TARGET_MACHINE" == "mipsel-musl" ]]; then
-    CONFIGFLAG+=" --with-float=soft"
-    CONFIGFLAG+=" --without-fp"
+
+  case "$XBPS_TARGET_MACHINE" in
+    ppc*)
+      conf+=" --enable-secureplt"
+      ;;
+    x86_64*)
+      conf+=" --enable-targets=x86_64-pep"
+      ;;
+    i686*)
+      conf+=" --enable-targets=x86_64-linux-gnu,x86_64-pep"
+      ;;
+  esac
+
+  # enable multilib on x86_64 glibc
+  if [[ "$XBPS_TARGET_MACHINE" == "x86_64" ]]; then
+    conf+=" --enable-multilib"
+  else
+    conf+=" --disable-multilib"
   fi
-  if [[ "${XBPS_TARGET_MACHINE%-musl}" == "x86_64" ]]; then
-    CONFIGFLAG+=" --enable-targets=x86_64-pep"
-  elif [[ "${XBPS_TARGET_MACHINE%-musl}" == "i686" ]]; then
-    CONFIGFLAG+=" --enable-64-bit-bfd"
-    CONFIGFLAG+=" --enable-targets=x86_64-linux-gnu,x86_64-pep"
-  fi
-  ./configure $CONFIGFLAG
+
+  # ensure softfloat on sf mips targets and set the default hash style
+  case "$XBPS_TARGET_MACHINE" in
+    mips*hf*)
+      conf+=" --enable-default-hash-style=sysv"
+      ;;
+    mips*)
+      conf+=" --without-fp --enable-default-hash-style=sysv"
+      ;;
+    *)
+      conf+=" --enable-default-hash-style=gnu"
+      ;;
+  esac
+
+  mkdir build \
+    && cd build
+  ../configure \
+    --build="$(_get_triplet)" \
+    --prefix="/usr" \
+    --libdir="/usr/lib" \
+    --mandir="/usr/share/man" \
+    --infodir="/usr/share/info" \
+    --disable-werror \
+    --disable-shared \
+    --disable-nls \
+    --enable-threads \
+    --enable-plugins \
+    --enable-relro \
+    --enable-gold \
+    --enable-deterministic-archives \
+    --enable-64-bit-bfd \
+    --enable-ld="default" \
+    --with-system-zlib \
+    --with-mmap \
+    --with-pic \
+    $conf
 }
 
 do_build() {
-  make "$makejobs"
-
-  # rebuild libiberty.a with -fPIC
-  cp -a libiberty libiberty-pic
-  make -C libiberty-pic clean
-  make CFLAGS="$CFLAGS -fPIC" -C libiberty-pic
-
-  # rebuild libbfd.a with -fPIC
-  cp -a bfd bfd-pic
-  make -C bfd-pic clean
-  # visibility=hidden to prevent 3rd-party shared libraries from exporting
-  # bfd non-stable API
-  make CFLAGS="$CFLAGS -fPIC -fvisibility=hidden" -C bfd-pic
-
-  # rebuild libopcodes.a with -fPIC
-  cp -a opcodes opcodes-pic
-  make -C opcodes-pic clean
-  make CFLAGS="$CFLAGS -fPIC" -C opcodes-pic
+  cd "$wrksrc/build" \
+    && make "$makejobs"
 }
 
-# if you enable this later, keep it off for `[[ -z "$CHROOT_READY" ]]`
+# there is a testsuite now, but e.g. ifunc tests all fail on musl and
+# also there are other tests that fail on different targets for fairly
+# harmless reasons and it's just too much effort to fix it all
 do_check() {
-  # seems like upstream forgot to include their new test-driver executable
-  # in their tarball...
-  :
+  [[ -n "$CHROOT_READY" ]] \
+    || return 0
+  : # cba for now
 }
 
 do_install() {
   local _triplet
-  make DESTDIR="$DESTDIR" tooldir="/usr" install
+
+  cd "$wrksrc/build"
+
+  _triplet="$(_get_triplet)"
+  make \
+    DESTDIR="$DESTDIR" \
+    tooldir="/usr" \
+    install
+
+  cd ..
 
   # remove ld (hardlink) and make a symlink to ld.bfd
   rm -f "$DESTDIR/usr/bin/ld"
@@ -112,16 +135,13 @@ do_install() {
   vinstall include/libiberty.h 644 usr/include
   vinstall include/demangle.h 644 usr/include
 
-  # install libraries rebuilt with -fPIC
-  vinstall libiberty-pic/libiberty.a 644 usr/lib
-  vinstall bfd-pic/libbfd.a 644 usr/lib
-  vinstall opcodes-pic/libopcodes.a 644 usr/lib
-
   # remove these symlinks, they are not ABI stable
   # programs should compile static to the .a file
   rm -f "$DESTDIR/usr/lib"/lib{bfd,opcodes}.so
-  echo "INPUT ( /usr/lib/libbfd.a -liberty -lz )" >"$DESTDIR/usr/lib/libbfd.so"
-  echo "INPUT ( /usr/lib/libopcodes.a -lbfd )" >"$DESTDIR/usr/lib/libopcodes.so"
+  echo "INPUT ( /usr/lib/libbfd.a -liberty -lz )" > \
+    "$DESTDIR/usr/lib/libbfd.so"
+  echo "INPUT ( /usr/lib/libopcodes.a -lbfd )" > \
+    "$DESTDIR/usr/lib/libopcodes.so"
 
   # remove useless manpages
   for f in dlltool \
@@ -132,7 +152,6 @@ do_install() {
   done
 
   # create triplet symlinks
-  _triplet=$(_get_triplet)
   for f in "$DESTDIR/usr/bin"/*; do
     ln -s "${f##*/}" "$DESTDIR/usr/bin/${XBPS_CROSS_TRIPLET:-$_triplet}-${f##*/}"
   done
